export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL";
export const CREATE_LIST_RESET = "CREATE_LIST_RESET";

export const MY_LISTS_REQUEST = "MY_LISTS_REQUEST";
export const MY_LISTS_SUCCESS = "MY_LISTS_SUCCESS";
export const MY_LISTS_FAIL = "MY_LISTS_FAIL";

export const ALL_LISTS_REQUEST = "ALL_LISTS_REQUEST";
export const ALL_LISTS_SUCCESS = "ALL_LISTS_SUCCESS";
export const ALL_LISTS_FAIL = "ALL_LISTS_FAIL";

export const UPDATE_LIST_REQUEST = "UPDATE_LIST_REQUEST";
export const UPDATE_LIST_SUCCESS = "UPDATE_LIST_SUCCESS";
export const UPDATE_LIST_RESET = "UPDATE_LIST_RESET";
export const UPDATE_LIST_FAIL = "UPDATE_LIST_FAIL";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_RESET = "DELETE_LIST_RESET";
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL";

export const LIST_DETAILS_REQUEST = "LIST_DETAILS_REQUEST";
export const LIST_DETAILS_SUCCESS = "LIST_DETAILS_SUCCESS";
export const LIST_DETAILS_FAIL = "LIST_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
