export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const REMOVE_ITEM_WISH_LIST = "REMOVE_ITEM_WISH_LIST";

export const WISH_LIST_ITEMS_RESET = "WISH_LIST_ITEMS_RESET";

export const SAVE_DETAILS = "SAVE_DETAILS";
